apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokube-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hellokube
  template:
    metadata:
      labels:
        app: hellokube
    spec:
      containers:
        - name: hello-kube
          image: acltabontabon/hello-kube
          ports:
            - containerPort: 8080
